### ISSUE TITLE
Hunt endpoint should return the intersection (if not empty) not the union

### ISSUE THREAD

**Issue by larsborn** [OALabs/hashdb#15]
The `/hunt` endpoint currently accepts multiple hashes. My assumption was that passing _more_ hashes to that endpoint, the number of results would decrease, because the DB has more hashes to automatically decide if a given algorithm is better suited for resolution. Instead, it seems that the API returns all possible hashing functions, similar to when I would have tried to hunt for the hashes separately and merge the responses.

Minimal Example: 

The body `{"hashes": [1676620]}` leads to
```json
{
    "hits": [
        {
            "algorithm": "revil_010F",
            "count": 8,
            "hitrate": 8.0
        }
    ]
}
```
and `{"hashes": [219106]}` leads to
```json
{
    "hits": [
        {
            "algorithm": "shl1_add",
            "count": 8,
            "hitrate": 8.0
        },
        {
            "algorithm": "revil_010F",
            "count": 6,
            "hitrate": 6.0
        }
    ]
}
```
But `{"hashes": [219106, 1676620]}` leads to 
```json
{
    "hits": [
        {
            "algorithm": "shl1_add",
            "count": 8,
            "hitrate": 4.0
        },
        {
            "algorithm": "revil_010F",
            "count": 14,
            "hitrate": 7.0
        }
    ]
}
```
as well. Ideally the last response would be the same as the first.

There might be a good reason `/hunt` behaves that way. In this case, could we get another endpoint that accepts multiple hashes and behaves as I suggested. Because if not, we would need to make N requests to the `/hunt` endpoint, one for each hash and intersect the results on the client side.

Context: this came up during developing the HashDB client for Ghidra and in particular, implement automatic REvil API resolution.

**Comment by herrcore** [comment]
This is a good point, and I see a few things here.

1. There is a clear bug with the way we do the count and hitrate which is caused by collisions in the table itself... if you hunt with a single hash the maximum count per table should be 1 and the maximum hitrate 100%. I have opened another issue to track this specifically: https://github.com/OALabs/hashdb/issues/17. I think this will solve your issue.

2. The reason we return the union rather than the intersection is that there are many cases where a hash list may include hashes from multiple algorithms and if we use the intersection we can end up up with no algorithms found. In this case we end up with multiple algorithms found and the "most likely" algorithm denoted by the higher hitrate (once the bug is fixed).

**Comment by herrcore** [comment]
Closing this with the bug fix: https://github.com/OALabs/hashdb/issues/17

Can re-open if this doesn't fix the issue.

**Comment by larsborn** [comment]
@herrcore thanks for the quick fix. Sadly behavior of the API didn't change at all. Here are a few quick command lines to check:

```
$ curl -sX POST https://hashdb.openanalysis.net/hunt -H "Content-Type: application/json" -d '{"hashes": [1676620]}' | jq -C
{
  "hits": [
    {
      "algorithm": "revil_010F",
      "count": 1,
      "hitrate": 1
    }
  ]
}

$ curl -sX POST https://hashdb.openanalysis.net/hunt -H "Content-Type: application/json" -d '{"hashes": [219106]}' | jq -C
{
  "hits": [
    {
      "algorithm": "shl1_add",
      "count": 1,
      "hitrate": 1
    },
    {
      "algorithm": "revil_010F",
      "count": 1,
      "hitrate": 1
    }
  ]
}

$ curl -sX POST https://hashdb.openanalysis.net/hunt -H "Content-Type: application/json" -d '{"hashes": [219106, 1676620]}' | jq -C
{
  "hits": [
    {
      "algorithm": "shl1_add",
      "count": 1,
      "hitrate": 0.5
    },
    {
      "algorithm": "revil_010F",
      "count": 2,
      "hitrate": 1
    }
  ]
}
```

Addressing your second point: something like that was what I though when I said "good reason". Maybe we could get a different endpoint then that returns the intersection? Or a GET parameter?

To give a bit more context: @huettenhain and I implemented the Ghidra Plugin for HashDB in a way that you collect a a list of hashes and then make the lookup (optionally allowing to look up the entire module). This list of hashes can be populated in a few different ways:

* clicking on specific values and executing our script
* collect all arguments passed as the n-th argument to a specific function
* crawl memory region for IAT-style API hashes
* manual entries

At least option 2 and 3 will lead to lists only containing hashes for one specific hash function.

But I also don't want to feature-creep this into the API! If you say this is too specific of a use case, we can also do one `/hunt` request per hash on the list and build the intersection on the client side. It would just be a lot slower because it would be `n` queries instead of one.

**Comment by larsborn** [comment]
For posterity (@herrcore and I just chatted): I was blind and didn't see the {{hitrate}} field. If you want to do what I want, you can just ignore all entries with a {{hitrate}} of less than {{1}}.
