### ISSUE TITLE
Supporting macOS APIs

### ISSUE THREAD

**Issue by mnrkbys** [OALabs/hashdb#30]
Hello.
hashdb.openanalysis.net is a great service.
But I was wondering that if it supports macOS APIs.
Unfortunately, it does not seems to support them at the moment.
Do you have any plan to support them in the future?

**Comment by herrcore** [comment]
I'm not sure what this means?

**Comment by mnrkbys** [comment]
Yes. That is correct.
I too believe that there is very little macOS malware that uses API hashing, but it is theoretically possible to implement.
This isssue is merely a question.
I am sorry if I have offended you.
