### ISSUE TITLE
Generic SmokeLoader string hashing

### ISSUE THREAD

**Issue by joaogodinho** [OALabs/hashdb#51]
SmokeLoader uses a ROL8 hashing as described in [rol8_xor_b0d4d06.py](/OALabs/hashdb/blob/main/algorithms/rol8_xor_b0d4d06.py), but my understanding is that the XOR key changes frequently.

I'd like to ask if it makes sense to add a generic `rol8` for Smoke (without XOR), or just modify this one and remove the current hardcoded XOR key (given we can query HashDB with an XOR already).

**Comment by herrcore** [comment]
Yes that's a great idea! Since the xor is at the end after the algo (and not used as a seed) we can take advantage of the hashdb xor feature. If you submit a PR I will gladly accept!
